---
- name: Join worker nodes to the Kubernetes cluster
  hosts: k8s_workers
  become: yes

  tasks:
    - name: Fetch join command from master
      delegate_to: 192.168.56.10
      slurp:
        src: /home/vagrant/join.sh
      register: join_script

    - name: Decode join command
      set_fact:
        join_cmd: "{{ join_script['content'] | b64decode | trim }}"

    - name: Run join command
      shell: "{{ join_cmd }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
