---
- name: Configure kernel modules and sysctl for Kubernetes networking
  hosts: all
  become: yes
  tasks:

    - name: Load br_netfilter module immediately
      modprobe:
        name: br_netfilter
        state: present

    - name: Ensure br_netfilter is loaded on boot
      copy:
        dest: /etc/modules-load.d/br_netfilter.conf
        content: "br_netfilter\n"
        owner: root
        group: root
        mode: '0644'

    - name: Create sysctl config for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl settings
      command: sysctl --system